# Generated by Django 4.2.30 on 2026-09-30 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Сумма от')),
                ('role', models.CharField(max_length=50, verbose_name='Роль согласующего')),
            ],
            options={
                'verbose_name': 'правило согласования решения',
                'verbose_name_plural': 'правила согласования решений',
                'ordering': ['min_amount'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=200, verbose_name='Статья бюджета')),
            ],
            options={
                'verbose_name': 'статья бюджета',
                'verbose_name_plural': 'статьи бюджета',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата')),
                ('kind', models.CharField(choices=[('regular', 'Договор'), ('framework', 'Рамочный договор'), ('specification', 'Спецификация / допсоглашение')], default='regular', max_length=20, verbose_name='Вид')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('signing', 'На подписании'), ('signed', 'Подписан'), ('execution', 'Исполняется'), ('executed', 'Исполнен'), ('closed', 'Закрыт'), ('cancelled', 'Аннулирован')], default='draft', max_length=20, verbose_name='Статус')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Действует до')),
                ('exported_1c_at', models.DateTimeField(blank=True, null=True, verbose_name='Выгружен в 1С')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='specifications', to='core.contract', verbose_name='Рамочный договор')),
            ],
            options={
                'verbose_name': 'договор',
                'verbose_name_plural': 'договоры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Наименование')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Кол-во')),
                ('unit', models.CharField(max_length=30, verbose_name='Ед. изм.')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Цена')),
                ('over_quantity_confirmed', models.BooleanField(default=False, verbose_name='Превышение подтверждено')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.contract')),
            ],
            options={
                'ordering': ['item__memo__number', 'item__line_no'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Подразделение')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель (согласующий СЗ)')),
            ],
            options={
                'verbose_name': 'подразделение',
                'verbose_name_plural': 'подразделения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(editable=False, unique=True, verbose_name='Номер')),
                ('justification', models.TextField(verbose_name='Обоснование')),
                ('required_date', models.DateField(verbose_name='Требуемый срок')),
                ('state', models.CharField(choices=[('draft', 'Черновик'), ('on_approval', 'На согласовании'), ('approved', 'Утверждена'), ('partially_approved', 'Утверждена частично'), ('rejected', 'Отклонена')], default='draft', max_length=30, verbose_name='Состояние документа')),
                ('approval_comment', models.TextField(blank=True, verbose_name='Комментарий согласующего')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Согласующий')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.department', verbose_name='Подразделение')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memos', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
            ],
            options={
                'verbose_name': 'служебная записка',
                'verbose_name_plural': 'служебные записки',
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='MemoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField(verbose_name='№ п/п')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Кол-во')),
                ('unit', models.CharField(default='шт', max_length=30, verbose_name='Ед. изм.')),
                ('required_date', models.DateField(verbose_name='Требуемый срок')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Ориентир. цена')),
                ('urgent', models.BooleanField(default=False, verbose_name='Срочно')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('on_approval', 'На согласовании'), ('rejected', 'Отклонена'), ('approved', 'Утверждена (в пуле)'), ('in_procurement', 'В закупке'), ('supplier_selected', 'Поставщик выбран'), ('partially_contracted', 'Частично в договоре'), ('contracted', 'В договоре'), ('partially_delivered', 'Частично поставлена'), ('delivered', 'Поставлена'), ('closed', 'Закрыта'), ('withdrawn', 'Отозвана')], db_index=True, default='draft', max_length=30, verbose_name='Статус')),
                ('status_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rejected', models.BooleanField(default=False)),
                ('reject_comment', models.CharField(blank=True, max_length=500, verbose_name='Причина отклонения')),
                ('withdrawn', models.BooleanField(default=False)),
                ('remainder_closed', models.BooleanField(default=False, verbose_name='Остаток закрыт')),
                ('closed', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('pool_note', models.CharField(blank=True, max_length=200, verbose_name='Пометка в пуле')),
                ('pool_since', models.DateTimeField(blank=True, null=True)),
                ('budget_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.budgetitem', verbose_name='Статья бюджета')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='Категория')),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.memo', verbose_name='СЗ')),
            ],
            options={
                'verbose_name': 'позиция потребности',
                'verbose_name_plural': 'позиции потребности',
                'ordering': ['memo__number', 'line_no'],
            },
        ),
        migrations.CreateModel(
            name='MemoTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'шаблон СЗ',
                'verbose_name_plural': 'шаблоны СЗ',
            },
        ),
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(editable=False, unique=True, verbose_name='Номер')),
                ('title', models.CharField(max_length=300, verbose_name='Наименование')),
                ('method', models.CharField(choices=[('rfq', 'Запрос КП'), ('tender', 'Тендер'), ('single', 'У единственного поставщика')], default='rfq', max_length=20, verbose_name='Способ')),
                ('kp_deadline', models.DateField(blank=True, null=True, verbose_name='Срок сбора КП')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('rfq', 'Запрос КП'), ('collecting', 'Сбор КП'), ('analysis', 'Анализ'), ('decided', 'Решение принято'), ('contracts', 'Договоры оформлены'), ('closed', 'Закрыта'), ('cancelled', 'Отменена')], default='draft', max_length=20, verbose_name='Статус')),
                ('decision_state', models.CharField(choices=[('none', 'Не сформировано'), ('on_approval', 'На согласовании'), ('approved', 'Утверждено'), ('rejected', 'Отклонено')], default='none', max_length=20, verbose_name='Решение')),
                ('decision_comment', models.TextField(blank=True, verbose_name='Комментарий к решению')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurements', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный закупщик')),
            ],
            options={
                'verbose_name': 'закупка',
                'verbose_name_plural': 'закупки',
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Кол-во к закупке')),
                ('state', models.CharField(choices=[('active', 'В лоте'), ('done', 'Отработана'), ('released', 'Возвращена в пул'), ('removed', 'Отозвана')], default='active', max_length=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_lines', to='core.memoitem')),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.procurement')),
            ],
            options={
                'ordering': ['item__memo__number', 'item__line_no'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Получено')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Действует до')),
                ('payment_terms', models.CharField(blank=True, max_length=300, verbose_name='Условия оплаты')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('source', models.CharField(choices=[('manual', 'Введено закупщиком'), ('excel', 'Импорт из Excel'), ('portal', 'Заполнено поставщиком')], default='manual', max_length=20)),
                ('attachment', models.FileField(blank=True, upload_to='quotes/', verbose_name='Файл КП')),
            ],
            options={
                'verbose_name': 'КП',
                'verbose_name_plural': 'КП',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('doc_number', models.CharField(blank=True, max_length=100, verbose_name='Документ 1С')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='core.contract')),
            ],
            options={
                'verbose_name': 'поступление',
                'verbose_name_plural': 'поступления',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=500, verbose_name='Причина')),
                ('state', models.CharField(choices=[('pending', 'Ожидает закупщика'), ('approved', 'Подтверждён'), ('rejected', 'Отклонён')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='core.memoitem')),
                ('procurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.procurement')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('bin', models.CharField(blank=True, max_length=20, verbose_name='БИН/ИИН')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('contact', models.CharField(blank=True, max_length=200, verbose_name='Контактное лицо')),
                ('code_1c', models.CharField(blank=True, max_length=50, verbose_name='Код в 1С')),
                ('categories', models.ManyToManyField(blank=True, to='core.category', verbose_name='Закрываемые категории')),
            ],
            options={
                'verbose_name': 'поставщик',
                'verbose_name_plural': 'поставщики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлен')),
                ('needs_correction', models.BooleanField(default=False, verbose_name='Требует корректировки')),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to='core.procurement')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfqs', to='core.supplier')),
            ],
            options={
                'verbose_name': 'запрос КП',
                'verbose_name_plural': 'запросы КП',
                'unique_together': {('procurement', 'supplier')},
            },
        ),
        migrations.CreateModel(
            name='ReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name', models.CharField(blank=True, max_length=500, verbose_name='Наименование из 1С')),
                ('raw_ref', models.CharField(blank=True, max_length=100, verbose_name='Ссылка из 1С')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Кол-во')),
                ('matched_by', models.CharField(choices=[('id', 'По ID позиции'), ('nomenclature', 'По номенклатуре и договору'), ('manual', 'Вручную')], default='id', max_length=20)),
                ('confirmed', models.BooleanField(default=True, verbose_name='Подтверждено')),
                ('contract_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_lines', to='core.contractline')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.receipt')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Цена за ед.')),
                ('offered_qty', models.DecimalField(blank=True, decimal_places=3, help_text='Пусто — на всё количество', max_digits=14, null=True, verbose_name='Предлагаемое кол-во')),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок поставки, дн.')),
                ('not_offered', models.BooleanField(default=False, verbose_name='Не предлагает')),
                ('is_analog', models.BooleanField(default=False, verbose_name='Аналог')),
                ('analog_description', models.CharField(blank=True, max_length=500, verbose_name='Описание аналога')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='Комментарий')),
                ('procurement_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_lines', to='core.procurementline')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.quote')),
            ],
            options={
                'unique_together': {('quote', 'procurement_line')},
            },
        ),
        migrations.AddField(
            model_name='quote',
            name='rfq',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='core.rfq'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Должность')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department', verbose_name='Подразделение')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'профили',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Сумма')),
                ('doc_number', models.CharField(blank=True, max_length=100, verbose_name='Документ 1С')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.contract')),
            ],
            options={
                'verbose_name': 'оплата',
                'verbose_name_plural': 'оплаты',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('url', models.CharField(blank=True, max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('unit', models.CharField(default='шт', max_length=30, verbose_name='Ед. изм.')),
                ('code_1c', models.CharField(blank=True, max_length=50, verbose_name='Код в 1С')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'номенклатура',
                'verbose_name_plural': 'номенклатура',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MemoTemplateLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Кол-во')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nomenclature')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.memotemplate')),
            ],
        ),
        migrations.AddField(
            model_name='memoitem',
            name='nomenclature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.nomenclature', verbose_name='Номенклатура'),
        ),
        migrations.CreateModel(
            name='HistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.contract')),
                ('memo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.memo')),
                ('procurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.procurement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Кол-во')),
                ('analog_state', models.CharField(choices=[('na', '—'), ('pending', 'Ждёт подтверждения инициатора'), ('accepted', 'Инициатор согласен'), ('declined', 'Инициатор не согласен')], default='na', max_length=20)),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_lines', to='core.procurement')),
                ('procurement_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_lines', to='core.procurementline')),
                ('quote_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decision_lines', to='core.quoteline')),
            ],
            options={
                'ordering': ['procurement_line__item__memo__number', 'procurement_line__item__line_no'],
            },
        ),
        migrations.CreateModel(
            name='DecisionApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, verbose_name='Роль')),
                ('state', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Согласовано'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='core.procurement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contractline',
            name='decision_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.decisionline'),
        ),
        migrations.AddField(
            model_name='contractline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_lines', to='core.memoitem'),
        ),
        migrations.AddField(
            model_name='contract',
            name='procurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='core.procurement', verbose_name='Закупка'),
        ),
        migrations.AddField(
            model_name='contract',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AddField(
            model_name='contract',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='core.supplier', verbose_name='Поставщик'),
        ),
        migrations.AddConstraint(
            model_name='procurementline',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'active')), fields=('item',), name='one_active_procurement_per_item'),
        ),
        migrations.AlterUniqueTogether(
            name='memoitem',
            unique_together={('memo', 'line_no')},
        ),
    ]
