# Generated by Django 4.2.30 on 2026-09-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='memo',
            name='status_code',
            field=models.CharField(db_index=True, default='draft', editable=False, max_length=20, verbose_name='Сводный статус'),
        ),
        migrations.AddField(
            model_name='memoitem',
            name='contracted_qty',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=14, verbose_name='В договорах'),
        ),
        migrations.AddField(
            model_name='memoitem',
            name='delivered_qty',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=14, verbose_name='Поставлено'),
        ),
    ]
