# Generated by Django 4.2.30 on 2026-10-09 06:15

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


RENAME_GROUPS = {
    "Согласующий": "Руководитель подразделения",
    "Закупщик": "Закупки (ОМТС)",
    "Директор": "Генеральный директор",
    "Финдиректор": "Финансы (ФЭО)",
    "Бухгалтер": "Бухгалтерия",
}

DEFAULT_CORRIDORS = [
    # code, name, color, max_amount, roles, sla, by_contract — как в макете ГРЭС
    ("g", "Зелёный", "g", 5_000_000, "Главный инженер", 1, False),
    ("y", "Жёлтый", "y", 50_000_000, "Главный инженер, Финансы (ФЭО), Закупки (ОМТС)", 2, False),
    ("r", "Красный", "r", None,
     "Главный инженер, Финансы (ФЭО), Закупки (ОМТС), Юристы (ЮО), Генеральный директор", 5, False),
    ("simple", "Упрощённый (по договору)", "b", None, "ПТО, Финансы (ФЭО)", 1, True),
]


def forwards(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    for old, new in RENAME_GROUPS.items():
        g = Group.objects.filter(name=old).first()
        if g and not Group.objects.filter(name=new).exists():
            g.name = new
            g.save()
    for name in ["Главный инженер", "Юристы (ЮО)", "ПТО"]:
        Group.objects.get_or_create(name=name)
    Corridor = apps.get_model("core", "Corridor")
    for code, name, color, max_amount, roles, sla, by_contract in DEFAULT_CORRIDORS:
        Corridor.objects.get_or_create(code=code, defaults=dict(
            name=name, color=color, max_amount=max_amount, roles=roles, sla_days=sla, by_contract=by_contract))


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_stored_quantities_and_counters'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('memo', 'Служебная записка'), ('quote', 'КП / счёт'), ('contract', 'Договор'), ('act', 'Акт / накладная'), ('other', 'Прочее')], default='other', max_length=20)),
                ('file', models.FileField(upload_to=core.models.attachment_path)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.contract')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Corridor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('color', models.CharField(default='g', help_text='g / y / r / b', max_length=10, verbose_name='Цвет')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Пусто — без верхней границы', max_digits=18, null=True, verbose_name='Сумма до (включительно), ₸')),
                ('roles', models.CharField(max_length=500, verbose_name='Согласующие роли (через запятую)')),
                ('sla_days', models.PositiveSmallIntegerField(default=1, verbose_name='Срок, рабочих дней')),
                ('by_contract', models.BooleanField(default=False, verbose_name='Для закупок по действующему договору')),
            ],
            options={
                'verbose_name': 'коридор согласования',
                'verbose_name_plural': 'коридоры согласования',
                'ordering': ['by_contract', 'max_amount'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('asked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Станция')),
            ],
            options={
                'verbose_name': 'станция',
                'verbose_name_plural': 'станции',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='ApprovalRule',
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Лимит на год, ₸'),
        ),
        migrations.AddField(
            model_name='decisionapproval',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок'),
        ),
        migrations.AddField(
            model_name='decisionapproval',
            name='escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historyentry',
            name='kind',
            field=models.CharField(blank=True, choices=[('', 'событие'), ('ok', 'согласовано'), ('q', 'вопрос'), ('bad', 'отклонено'), ('auto', 'система'), ('comment', 'комментарий')], max_length=10),
        ),
        migrations.AddField(
            model_name='memo',
            name='budget_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.budgetitem', verbose_name='Статья бюджета'),
        ),
        migrations.AddField(
            model_name='memo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='memo',
            name='title',
            field=models.CharField(blank=True, help_text='Если пусто — по первой позиции', max_length=300, verbose_name='Название заявки'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='decision_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procurement',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=300, verbose_name='Условия оплаты'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='method',
            field=models.CharField(choices=[('rfq', 'Запрос ценовых предложений'), ('tender', 'Открытый тендер'), ('single', 'Из одного источника'), ('framework', 'Из одного источника (рамочный)'), ('contract', 'По действующему договору')], default='rfq', max_length=20, verbose_name='Способ'),
        ),
        migrations.AddField(
            model_name='question',
            name='memo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.memo'),
        ),
        migrations.AddField(
            model_name='question',
            name='procurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.procurement'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='memo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.memo'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='procurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.procurement'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memo',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.station', verbose_name='Станция'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='corridor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.corridor', verbose_name='Коридор'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.station', verbose_name='Станция'),
        ),
        migrations.AddField(
            model_name='profile',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.station', verbose_name='Станция'),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
]
