# Generated by Django 4.2.30 on 2026-10-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_grees_corridors_stations'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoitem',
            name='spec',
            field=models.CharField(blank=True, max_length=500, verbose_name='Марка / ГОСТ / характеристики'),
        ),
    ]
